spring:
  config:
    activate:
      on-profile: mysql
  autoconfigure:
    exclude: []
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/xinghe?useSSL=false&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:xinghe}
    password: ${SPRING_DATASOURCE_PASSWORD:change-me}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
